/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  publicDocSidebar: [
    "index",
    {
      type: "category",
      label: "Public Networks",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "public-networks" }],
    },
  ],
  privateDocSidebar: [
    {
      type: "category",
      label: "Private Networks",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "private-networks" }],
    },
  ],
};

module.exports = sidebars;
